version: "2.1"
orbs:
  flanscan: gabanz/flanscan@dev:alpha
jobs:
  test-orb:
    build:
      docker:
        - image: cimg/base:2020.01
    steps:
      - checkout
      - flanscan/build
      - flanscan/scan
