version: "2.1"
orbs:
  flanscan: gabanz/flanscan@dev:alpha
workflows:
  test:
    jobs:
      - flanscan/aws:
          format: json
          ip: 9.9.9.9
          bucket: flanscan20201021
          accesskey: abc123
          secret: abc123
      - flanscan/gcp:
          format: html
          ip: 8.8.8.8
          bucket: flanscan20201021
          cred: key.json
