version: "2.1"
orbs:
  flanscan: gabanz/flanscan@dev:alpha
workflows:
  test:
    jobs:
      - flanscan/start:
          format: json
          ip: 9.9.9.9
          upload: aws
          bucket: flanscan20201021
