version: "2.1"
orbs:
  flanscan: gabanz/flanscan@dev:alpha

jobs:
  checkout:
    docker: 
      - image: cimg/base:2020.01
    steps:
      - checkout

workflows:
  test:
    jobs:
      - checkout
#      - flanscan/aws:
#          format: html
#          ip: 9.9.9.9
#          bucket: flanscan20201021
#          accesskey: abc123
#          secret: abc123
      - flanscan/gcp:
          format: md
          ip: 8.8.8.8
          bucket: flanscan20201021
          cred: "key.json"
          requires:
            - checkout
